#
# Module manifest for module 'ILAssembler'
#
# Generated by: Patrick Meinecke
#
# Generated on: 8/9/2020
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ILAssembler.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '6519b695-a59c-4d5f-892d-ae60d4b49fdf'

# Author of this module
Author = 'Patrick Meinecke'

# Company or vendor of this module
CompanyName = 'Community'

# Copyright statement for this module
Copyright = '(c) 2020 Patrick Meinecke. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Generate an invokable delegate from intermediate language (IL) instructions.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'None'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport =
    'ldloc.auto', 'stloc.auto', 'ldloca.auto', 'add', 'nop', 'ldarg.0', 'ldarg.1',
    'ldarg.2', 'ldarg.3', 'ldloc.0', 'ldloc.1', 'ldloc.2', 'ldloc.3', 'stloc.0',
    'stloc.1', 'stloc.2', 'stloc.3', 'ldarg.s', 'ldarga.s', 'starg.s', 'ldloc.s',
    'ldloca.s', 'stloc.s', 'ldnull', 'ldc.i4.m1', 'ldc.i4.0', 'ldc.i4.1', 'ldc.i4.2',
    'ldc.i4.3', 'ldc.i4.4', 'ldc.i4.5', 'ldc.i4.6', 'ldc.i4.7', 'ldc.i4.8', 'ldc.i4.s',
    'ldc.i4', 'ldc.i8', 'ldc.r4', 'ldc.r8', 'dup', 'pop', 'jmp', 'call', 'ret',
    'br.s', 'brfalse.s', 'brtrue.s', 'beq.s', 'bge.s', 'bgt.s', 'ble.s', 'blt.s',
    'bne.un.s', 'bge.un.s', 'bgt.un.s', 'ble.un.s', 'blt.un.s', 'br', 'brfalse',
    'brtrue', 'beq', 'bge', 'bgt', 'ble', 'blt', 'bne.un', 'bge.un', 'bgt.un', 'ble.un',
    'blt.un', 'ldind.i1', 'ldind.u1', 'ldind.i2', 'ldind.u2', 'ldind.i4', 'calli',
    'ldind.u4', 'ldind.i8', 'ldind.i', 'ldind.r4', 'ldind.r8', 'ldind.ref', 'stind.ref',
    'stind.i1', 'stind.i2', 'stind.i4', 'stind.i8', 'stind.r4', 'stind.r8', 'sub', 'mul',
    'div', 'div.un', 'rem', 'rem.un', 'and', 'or', 'xor', 'shl', 'shr', 'shr.un', 'neg',
    'not', 'conv.i1', 'conv.i2', 'conv.i4', 'conv.i8', 'conv.r4', 'conv.r8', 'conv.u4',
    'conv.u8', 'callvirt', 'cpobj', 'ldobj', 'ldstr', 'newobj', 'castclass', 'isinst',
    'conv.r.un', 'unbox', 'throw', 'ldfld', 'ldflda', 'stfld', 'ldsfld', 'ldsflda',
    'stsfld', 'stobj', 'conv.ovf.i1.un', 'conv.ovf.i2.un', 'conv.ovf.i4.un', 'conv.ovf.i8.un',
    'conv.ovf.u1.un', 'conv.ovf.u2.un', 'conv.ovf.u4.un', 'conv.ovf.u8.un', 'conv.ovf.i.un',
    'conv.ovf.u.un', 'box', 'newarr', 'ldlen', 'ldelema', 'ldelem.i1', 'ldelem.u1', 'ldelem.i2',
    'ldelem.u2', 'ldelem.i4', 'ldelem.u4', 'ldelem.i8', 'ldelem.i', 'ldelem.r4', 'ldelem.r8',
    'ldelem.ref', 'stelem.i', 'stelem.i1', 'stelem.i2', 'stelem.i4', 'stelem.i8', 'stelem.r4',
    'stelem.r8', 'stelem.ref', 'ldelem', 'stelem', 'unbox.any', 'conv.ovf.i1', 'conv.ovf.u1',
    'conv.ovf.i2', 'conv.ovf.u2', 'conv.ovf.i4', 'conv.ovf.u4', 'conv.ovf.i8', 'conv.ovf.u8',
    'refanyval', 'ckfinite', 'mkrefany', 'ldtoken', 'conv.u2', 'conv.u1', 'conv.i', 'conv.ovf.i',
    'conv.ovf.u', 'add.ovf', 'add.ovf.un', 'mul.ovf', 'mul.ovf.un', 'sub.ovf', 'sub.ovf.un',
    'endfinally', 'endfault', 'leave', 'leave.s', 'stind.i', 'conv.u', 'arglist', 'ceq', 'cgt', 'cgt.un',
    'clt', 'clt.un', 'ldftn', 'ldvirtftn', 'ldarg', 'ldarga', 'starg', 'ldloc', 'ldloca',
    'stloc', 'localloc', 'endfilter', 'unaligned.', 'volatile.', 'tail.', 'initobj', 'constrained.',
    'cpblk', 'initblk', 'rethrow', 'sizeof', 'refanytype', 'readonly.', 'switch'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = 'New-ILDelegate'

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'il'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'il', 'cil', 'msil'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/SeeminglyScience/ILAssembler/blob/master/LICENSE.txt'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/SeeminglyScience/ILAssembler'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
