using System.Collections.Generic;
using System.Reflection.Metadata;
using ILAssembler.OpCodes;

namespace ILAssembler
{
    internal sealed class OpCodeStore
    {
        private static readonly Dictionary<string, OpCodeInfo> s_opCodes = new();

        static OpCodeStore()
        {
            Add(new AutoLocalOpCodeInfo("ldloc.auto", isSet: false, isAddress: false));
            Add(new AutoLocalOpCodeInfo("stloc.auto", isSet: true, isAddress: false));
            Add(new AutoLocalOpCodeInfo("ldloca.auto", isSet: false, isAddress: true));
            Add(new NoOperandOpCodeInfo("add", ILOpCode.Add));
            Add(new NoOperandOpCodeInfo("nop", ILOpCode.Nop));
            Add(new NoOperandOpCodeInfo("break", ILOpCode.Break));
            Add(new NoOperandOpCodeInfo("ldarg.0", ILOpCode.Ldarg_0));
            Add(new NoOperandOpCodeInfo("ldarg.1", ILOpCode.Ldarg_1));
            Add(new NoOperandOpCodeInfo("ldarg.2", ILOpCode.Ldarg_2));
            Add(new NoOperandOpCodeInfo("ldarg.3", ILOpCode.Ldarg_3));
            Add(new NoOperandOpCodeInfo("ldloc.0", ILOpCode.Ldloc_0));
            Add(new NoOperandOpCodeInfo("ldloc.1", ILOpCode.Ldloc_1));
            Add(new NoOperandOpCodeInfo("ldloc.2", ILOpCode.Ldloc_2));
            Add(new NoOperandOpCodeInfo("ldloc.3", ILOpCode.Ldloc_3));
            Add(new NoOperandOpCodeInfo("stloc.0", ILOpCode.Stloc_0));
            Add(new NoOperandOpCodeInfo("stloc.1", ILOpCode.Stloc_1));
            Add(new NoOperandOpCodeInfo("stloc.2", ILOpCode.Stloc_2));
            Add(new NoOperandOpCodeInfo("stloc.3", ILOpCode.Stloc_3));
            Add(new ByteOpCodeInfo("ldarg.s", ILOpCode.Ldarg_s));
            Add(new ByteOpCodeInfo("ldarga.s", ILOpCode.Ldarga_s));
            Add(new ByteOpCodeInfo("starg.s", ILOpCode.Starg_s));
            Add(new ByteOpCodeInfo("ldloc.s", ILOpCode.Ldloc_s));
            Add(new ByteOpCodeInfo("ldloca.s", ILOpCode.Ldloca_s));
            Add(new ByteOpCodeInfo("stloc.s", ILOpCode.Stloc_s));
            Add(new NoOperandOpCodeInfo("ldnull", ILOpCode.Ldnull));
            Add(new NoOperandOpCodeInfo("ldc.i4.m1", ILOpCode.Ldc_i4_m1));
            Add(new NoOperandOpCodeInfo("ldc.i4.0", ILOpCode.Ldc_i4_0));
            Add(new NoOperandOpCodeInfo("ldc.i4.1", ILOpCode.Ldc_i4_1));
            Add(new NoOperandOpCodeInfo("ldc.i4.2", ILOpCode.Ldc_i4_2));
            Add(new NoOperandOpCodeInfo("ldc.i4.3", ILOpCode.Ldc_i4_3));
            Add(new NoOperandOpCodeInfo("ldc.i4.4", ILOpCode.Ldc_i4_4));
            Add(new NoOperandOpCodeInfo("ldc.i4.5", ILOpCode.Ldc_i4_5));
            Add(new NoOperandOpCodeInfo("ldc.i4.6", ILOpCode.Ldc_i4_6));
            Add(new NoOperandOpCodeInfo("ldc.i4.7", ILOpCode.Ldc_i4_7));
            Add(new NoOperandOpCodeInfo("ldc.i4.8", ILOpCode.Ldc_i4_8));
            Add(new ByteOpCodeInfo("ldc.i4.s", ILOpCode.Ldc_i4_s));
            Add(new Int32OpCodeInfo("ldc.i4", ILOpCode.Ldc_i4));
            Add(new Int64OpCodeInfo("ldc.i8", ILOpCode.Ldc_i8));
            Add(new NoOperandOpCodeInfo("ldc.r4", ILOpCode.Ldc_r4));
            Add(new DoubleOpCodeInfo("ldc.r8", ILOpCode.Ldc_r8));
            Add(new NoOperandOpCodeInfo("dup", ILOpCode.Dup));
            Add(new NoOperandOpCodeInfo("pop", ILOpCode.Pop));
            Add(new MethodOpCodeInfo("jmp", ILOpCode.Jmp));
            Add(new MethodOpCodeInfo("call", ILOpCode.Call));
            Add(new CalliOpCodeInfo("calli", ILOpCode.Calli));
            Add(new NoOperandOpCodeInfo("ret", ILOpCode.Ret));
            Add(new BranchOpCodeInfo("br.s", ILOpCode.Br_s));
            Add(new BranchOpCodeInfo("brfalse.s", ILOpCode.Brfalse_s));
            Add(new BranchOpCodeInfo("brtrue.s", ILOpCode.Brtrue_s));
            Add(new BranchOpCodeInfo("beq.s", ILOpCode.Beq_s));
            Add(new BranchOpCodeInfo("bge.s", ILOpCode.Bge_s));
            Add(new BranchOpCodeInfo("bgt.s", ILOpCode.Bgt_s));
            Add(new BranchOpCodeInfo("ble.s", ILOpCode.Ble_s));
            Add(new BranchOpCodeInfo("blt.s", ILOpCode.Blt_s));
            Add(new BranchOpCodeInfo("bne.un.s", ILOpCode.Bne_un_s));
            Add(new BranchOpCodeInfo("bge.un.s", ILOpCode.Bge_un_s));
            Add(new BranchOpCodeInfo("bgt.un.s", ILOpCode.Bgt_un_s));
            Add(new BranchOpCodeInfo("ble.un.s", ILOpCode.Ble_un_s));
            Add(new BranchOpCodeInfo("blt.un.s", ILOpCode.Blt_un_s));
            Add(new BranchOpCodeInfo("br", ILOpCode.Br));
            Add(new BranchOpCodeInfo("brfalse", ILOpCode.Brfalse));
            Add(new BranchOpCodeInfo("brtrue", ILOpCode.Brtrue));
            Add(new BranchOpCodeInfo("beq", ILOpCode.Beq));
            Add(new BranchOpCodeInfo("bge", ILOpCode.Bge));
            Add(new BranchOpCodeInfo("bgt", ILOpCode.Bgt));
            Add(new BranchOpCodeInfo("ble", ILOpCode.Ble));
            Add(new BranchOpCodeInfo("blt", ILOpCode.Blt));
            Add(new BranchOpCodeInfo("bne.un", ILOpCode.Bne_un));
            Add(new BranchOpCodeInfo("bge.un", ILOpCode.Bge_un));
            Add(new BranchOpCodeInfo("bgt.un", ILOpCode.Bgt_un));
            Add(new BranchOpCodeInfo("ble.un", ILOpCode.Ble_un));
            Add(new BranchOpCodeInfo("blt.un", ILOpCode.Blt_un));
            Add(new NoOperandOpCodeInfo("ldind.i1", ILOpCode.Ldind_i1));
            Add(new NoOperandOpCodeInfo("ldind.u1", ILOpCode.Ldind_u1));
            Add(new NoOperandOpCodeInfo("ldind.i2", ILOpCode.Ldind_i2));
            Add(new NoOperandOpCodeInfo("ldind.u2", ILOpCode.Ldind_u2));
            Add(new NoOperandOpCodeInfo("ldind.i4", ILOpCode.Ldind_i4));
            Add(new NoOperandOpCodeInfo("ldind.u4", ILOpCode.Ldind_u4));
            Add(new NoOperandOpCodeInfo("ldind.i8", ILOpCode.Ldind_i8));
            Add(new NoOperandOpCodeInfo("ldind.i", ILOpCode.Ldind_i));
            Add(new SingleOpCodeInfo("ldind.r4", ILOpCode.Ldind_r4));
            Add(new NoOperandOpCodeInfo("ldind.r8", ILOpCode.Ldind_r8));
            Add(new NoOperandOpCodeInfo("ldind.ref", ILOpCode.Ldind_ref));
            Add(new NoOperandOpCodeInfo("stind.ref", ILOpCode.Stind_ref));
            Add(new NoOperandOpCodeInfo("stind.i1", ILOpCode.Stind_i1));
            Add(new NoOperandOpCodeInfo("stind.i2", ILOpCode.Stind_i2));
            Add(new NoOperandOpCodeInfo("stind.i4", ILOpCode.Stind_i4));
            Add(new NoOperandOpCodeInfo("stind.i8", ILOpCode.Stind_i8));
            Add(new NoOperandOpCodeInfo("stind.r4", ILOpCode.Stind_r4));
            Add(new NoOperandOpCodeInfo("stind.r8", ILOpCode.Stind_r8));
            Add(new NoOperandOpCodeInfo("sub", ILOpCode.Sub));
            Add(new NoOperandOpCodeInfo("mul", ILOpCode.Mul));
            Add(new NoOperandOpCodeInfo("div", ILOpCode.Div));
            Add(new NoOperandOpCodeInfo("div.un", ILOpCode.Div_un));
            Add(new NoOperandOpCodeInfo("rem", ILOpCode.Rem));
            Add(new NoOperandOpCodeInfo("rem.un", ILOpCode.Rem_un));
            Add(new NoOperandOpCodeInfo("and", ILOpCode.And));
            Add(new NoOperandOpCodeInfo("or", ILOpCode.Or));
            Add(new NoOperandOpCodeInfo("xor", ILOpCode.Xor));
            Add(new NoOperandOpCodeInfo("shl", ILOpCode.Shl));
            Add(new NoOperandOpCodeInfo("shr", ILOpCode.Shr));
            Add(new NoOperandOpCodeInfo("shr.un", ILOpCode.Shr_un));
            Add(new NoOperandOpCodeInfo("neg", ILOpCode.Neg));
            Add(new NoOperandOpCodeInfo("not", ILOpCode.Not));
            Add(new NoOperandOpCodeInfo("conv.i1", ILOpCode.Conv_i1));
            Add(new NoOperandOpCodeInfo("conv.i2", ILOpCode.Conv_i2));
            Add(new NoOperandOpCodeInfo("conv.i4", ILOpCode.Conv_i4));
            Add(new NoOperandOpCodeInfo("conv.i8", ILOpCode.Conv_i8));
            Add(new NoOperandOpCodeInfo("conv.r4", ILOpCode.Conv_r4));
            Add(new NoOperandOpCodeInfo("conv.r8", ILOpCode.Conv_r8));
            Add(new NoOperandOpCodeInfo("conv.u4", ILOpCode.Conv_u4));
            Add(new NoOperandOpCodeInfo("conv.u8", ILOpCode.Conv_u8));
            Add(new MethodOpCodeInfo("callvirt", ILOpCode.Callvirt));
            Add(new TypeOpCodeInfo("cpobj", ILOpCode.Cpobj));
            Add(new TypeOpCodeInfo("ldobj", ILOpCode.Ldobj));
            Add(new StringOpCodeInfo("ldstr", ILOpCode.Ldstr));
            Add(new ConstructorOpCodeInfo("newobj", ILOpCode.Newobj));
            Add(new TypeOpCodeInfo("castclass", ILOpCode.Castclass));
            Add(new TypeOpCodeInfo("isinst", ILOpCode.Isinst));
            Add(new NoOperandOpCodeInfo("conv.r.un", ILOpCode.Conv_r_un));
            Add(new TypeOpCodeInfo("unbox", ILOpCode.Unbox));
            Add(new NoOperandOpCodeInfo("throw", ILOpCode.Throw));
            Add(new FieldOpCodeInfo("ldfld", ILOpCode.Ldfld));
            Add(new FieldOpCodeInfo("ldflda", ILOpCode.Ldflda));
            Add(new FieldOpCodeInfo("stfld", ILOpCode.Stfld));
            Add(new FieldOpCodeInfo("ldsfld", ILOpCode.Ldsfld));
            Add(new FieldOpCodeInfo("ldsflda", ILOpCode.Ldsflda));
            Add(new FieldOpCodeInfo("stsfld", ILOpCode.Stsfld));
            Add(new TypeOpCodeInfo("stobj", ILOpCode.Stobj));
            Add(new NoOperandOpCodeInfo("conv.ovf.i1.un", ILOpCode.Conv_ovf_i1_un));
            Add(new NoOperandOpCodeInfo("conv.ovf.i2.un", ILOpCode.Conv_ovf_i2_un));
            Add(new NoOperandOpCodeInfo("conv.ovf.i4.un", ILOpCode.Conv_ovf_i4_un));
            Add(new NoOperandOpCodeInfo("conv.ovf.i8.un", ILOpCode.Conv_ovf_i8_un));
            Add(new NoOperandOpCodeInfo("conv.ovf.u1.un", ILOpCode.Conv_ovf_u1_un));
            Add(new NoOperandOpCodeInfo("conv.ovf.u2.un", ILOpCode.Conv_ovf_u2_un));
            Add(new NoOperandOpCodeInfo("conv.ovf.u4.un", ILOpCode.Conv_ovf_u4_un));
            Add(new NoOperandOpCodeInfo("conv.ovf.u8.un", ILOpCode.Conv_ovf_u8_un));
            Add(new NoOperandOpCodeInfo("conv.ovf.i.un", ILOpCode.Conv_ovf_i_un));
            Add(new NoOperandOpCodeInfo("conv.ovf.u.un", ILOpCode.Conv_ovf_u_un));
            Add(new TypeOpCodeInfo("box", ILOpCode.Box));
            Add(new TypeOpCodeInfo("newarr", ILOpCode.Newarr));
            Add(new NoOperandOpCodeInfo("ldlen", ILOpCode.Ldlen));
            Add(new TypeOpCodeInfo("ldelema", ILOpCode.Ldelema));
            Add(new NoOperandOpCodeInfo("ldelem.i1", ILOpCode.Ldelem_i1));
            Add(new NoOperandOpCodeInfo("ldelem.u1", ILOpCode.Ldelem_u1));
            Add(new NoOperandOpCodeInfo("ldelem.i2", ILOpCode.Ldelem_i2));
            Add(new NoOperandOpCodeInfo("ldelem.u2", ILOpCode.Ldelem_u2));
            Add(new NoOperandOpCodeInfo("ldelem.i4", ILOpCode.Ldelem_i4));
            Add(new NoOperandOpCodeInfo("ldelem.u4", ILOpCode.Ldelem_u4));
            Add(new NoOperandOpCodeInfo("ldelem.i8", ILOpCode.Ldelem_i8));
            Add(new NoOperandOpCodeInfo("ldelem.i", ILOpCode.Ldelem_i));
            Add(new NoOperandOpCodeInfo("ldelem.r4", ILOpCode.Ldelem_r4));
            Add(new NoOperandOpCodeInfo("ldelem.r8", ILOpCode.Ldelem_r8));
            Add(new NoOperandOpCodeInfo("ldelem.ref", ILOpCode.Ldelem_ref));
            Add(new NoOperandOpCodeInfo("stelem.i", ILOpCode.Stelem_i));
            Add(new NoOperandOpCodeInfo("stelem.i1", ILOpCode.Stelem_i1));
            Add(new NoOperandOpCodeInfo("stelem.i2", ILOpCode.Stelem_i2));
            Add(new NoOperandOpCodeInfo("stelem.i4", ILOpCode.Stelem_i4));
            Add(new NoOperandOpCodeInfo("stelem.i8", ILOpCode.Stelem_i8));
            Add(new NoOperandOpCodeInfo("stelem.r4", ILOpCode.Stelem_r4));
            Add(new NoOperandOpCodeInfo("stelem.r8", ILOpCode.Stelem_r8));
            Add(new NoOperandOpCodeInfo("stelem.ref", ILOpCode.Stelem_ref));
            Add(new TypeOpCodeInfo("ldelem", ILOpCode.Ldelem));
            Add(new TypeOpCodeInfo("stelem", ILOpCode.Stelem));
            Add(new TypeOpCodeInfo("unbox.any", ILOpCode.Unbox_any));
            Add(new NoOperandOpCodeInfo("conv.ovf.i1", ILOpCode.Conv_ovf_i1));
            Add(new NoOperandOpCodeInfo("conv.ovf.u1", ILOpCode.Conv_ovf_u1));
            Add(new NoOperandOpCodeInfo("conv.ovf.i2", ILOpCode.Conv_ovf_i2));
            Add(new NoOperandOpCodeInfo("conv.ovf.u2", ILOpCode.Conv_ovf_u2));
            Add(new NoOperandOpCodeInfo("conv.ovf.i4", ILOpCode.Conv_ovf_i4));
            Add(new NoOperandOpCodeInfo("conv.ovf.u4", ILOpCode.Conv_ovf_u4));
            Add(new NoOperandOpCodeInfo("conv.ovf.i8", ILOpCode.Conv_ovf_i8));
            Add(new NoOperandOpCodeInfo("conv.ovf.u8", ILOpCode.Conv_ovf_u8));
            Add(new TypeOpCodeInfo("refanyval", ILOpCode.Refanyval));
            Add(new NoOperandOpCodeInfo("ckfinite", ILOpCode.Ckfinite));
            Add(new TypeOpCodeInfo("mkrefany", ILOpCode.Mkrefany));
            Add(new AnyTokenOpCodeInfo("ldtoken", ILOpCode.Ldtoken));
            Add(new NoOperandOpCodeInfo("conv.u2", ILOpCode.Conv_u2));
            Add(new NoOperandOpCodeInfo("conv.u1", ILOpCode.Conv_u1));
            Add(new NoOperandOpCodeInfo("conv.i", ILOpCode.Conv_i));
            Add(new NoOperandOpCodeInfo("conv.ovf.i", ILOpCode.Conv_ovf_i));
            Add(new NoOperandOpCodeInfo("conv.ovf.u", ILOpCode.Conv_ovf_u));
            Add(new NoOperandOpCodeInfo("add.ovf", ILOpCode.Add_ovf));
            Add(new NoOperandOpCodeInfo("add.ovf.un", ILOpCode.Add_ovf_un));
            Add(new NoOperandOpCodeInfo("mul.ovf", ILOpCode.Mul_ovf));
            Add(new NoOperandOpCodeInfo("mul.ovf.un", ILOpCode.Mul_ovf_un));
            Add(new NoOperandOpCodeInfo("sub.ovf", ILOpCode.Sub_ovf));
            Add(new NoOperandOpCodeInfo("sub.ovf.un", ILOpCode.Sub_ovf_un));
            Add(new NoOperandOpCodeInfo("endfinally", ILOpCode.Endfinally));
            Add(new NoOperandOpCodeInfo("endfault", ILOpCode.Endfinally));
            Add(new BranchOpCodeInfo("leave", ILOpCode.Leave));
            Add(new BranchOpCodeInfo("leave.s", ILOpCode.Leave_s));
            Add(new NoOperandOpCodeInfo("stind.i", ILOpCode.Stind_i));
            Add(new NoOperandOpCodeInfo("conv.u", ILOpCode.Conv_u));
            Add(new NoOperandOpCodeInfo("arglist", ILOpCode.Arglist));
            Add(new NoOperandOpCodeInfo("ceq", ILOpCode.Ceq));
            Add(new NoOperandOpCodeInfo("cgt", ILOpCode.Cgt));
            Add(new NoOperandOpCodeInfo("cgt.un", ILOpCode.Cgt_un));
            Add(new NoOperandOpCodeInfo("clt", ILOpCode.Clt));
            Add(new NoOperandOpCodeInfo("clt.un", ILOpCode.Clt_un));
            Add(new MethodOpCodeInfo("ldftn", ILOpCode.Ldftn));
            Add(new MethodOpCodeInfo("ldvirtftn", ILOpCode.Ldvirtftn));
            Add(new Int32OpCodeInfo("ldarg", ILOpCode.Ldarg));
            Add(new Int32OpCodeInfo("ldarga", ILOpCode.Ldarga));
            Add(new Int32OpCodeInfo("starg", ILOpCode.Starg));
            Add(new Int32OpCodeInfo("ldloc", ILOpCode.Ldloc));
            Add(new Int32OpCodeInfo("ldloca", ILOpCode.Ldloca));
            Add(new Int32OpCodeInfo("stloc", ILOpCode.Stloc));
            Add(new NoOperandOpCodeInfo("localloc", ILOpCode.Localloc));
            Add(new NoOperandOpCodeInfo("endfilter", ILOpCode.Endfilter));
            Add(new ByteOpCodeInfo("unaligned.", ILOpCode.Unaligned));
            Add(new NoOperandOpCodeInfo("volatile.", ILOpCode.Volatile));
            Add(new NoOperandOpCodeInfo("tail.", ILOpCode.Tail));
            Add(new TypeOpCodeInfo("initobj", ILOpCode.Initobj));
            Add(new TypeOpCodeInfo("constrained.", ILOpCode.Constrained));
            Add(new NoOperandOpCodeInfo("cpblk", ILOpCode.Cpblk));
            Add(new NoOperandOpCodeInfo("initblk", ILOpCode.Initblk));
            Add(new NoOperandOpCodeInfo("rethrow", ILOpCode.Rethrow));
            Add(new TypeOpCodeInfo("sizeof", ILOpCode.Sizeof));
            Add(new NoOperandOpCodeInfo("refanytype", ILOpCode.Refanytype));
            Add(new NoOperandOpCodeInfo("readonly.", ILOpCode.Readonly));
            Add(new SwitchOpCodeInfo("switch", ILOpCode.Switch));
            Add(new EmitOpCodeInfo());
        }

        public static bool TryGetOpCodeInfo(string name, out OpCodeInfo? info)
        {
            return s_opCodes.TryGetValue(name, out info);
        }

        private static void Add(OpCodeInfo info)
        {
            s_opCodes.Add(info.Name, info);
        }
    }
}
