name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

defaults:
    run:
      shell: pwsh

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, macos-latest, windows-latest ]
    steps:
    - uses: actions/checkout@v1
    - name: Enable null conditional operators
      run: Enable-ExperimentalFeature PSNullConditionalOperators -ErrorAction Ignore -WarningAction Ignore
    - name: Test and Build
      run: ./build.ps1 -Force
    - uses: actions/upload-artifact@v1
      with:
        name: ILAssembler
        path: ./Release/ILAssembler
