name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest ]
    defaults:
        run:
          shell: pwsh
    steps:
    - uses: actions/checkout@v1
    - name: Enable null conditional operators
    - run: Enable-ExperimentalFeature PSNullConditionalOperators -ErrorAction Ignore -WarningAction Ignore
    - name: Test and Build
    - run: ./build.ps1 -Force
    - uses: actions/upload-artifact@v1
      with:
        name: ILAssembler
        path: ./Release/ILAssembler
