name: publish
on:
  release:
      types: [ published ]
jobs:
  build:
    name: Publish
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test and Build
      shell: pwsh
      run: ./build.ps1 -Force -Publish
      env:
        GALLERY_API_KEY: ${{ secrets.GALLERY_API_KEY }}
